version: '3'

services:
  server:
    build: ./server
    container_name: tcp_server
    ports:
      - "12345:12345"

  client:
    build: ./client
    container_name: tcp_client
    depends_on:
      - server
