apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 5
  selector:
    matchLabels:
      app: distributed-app
      role: client
  template:
    metadata:
      labels:
        app: distributed-app
        role: client
    spec:
      containers:
        - name: client
          image: my-distributed-app
          imagePullPolicy: Never
          command: ["python3", "client/client.py"]
          env:
            - name: SERVER_URL
              value: "http://server-service:8000"
